swagger:

  defaultPipe: null
  swaggerControllerPipe: swagger_controllers

  # https://github.com/apigee-127/bagpipes
  bagpipes:

    _router:
      name: swagger_router
      mockControllersDirs: [ . ]
      controllersDirs: [ . ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    swagger_controllers:
      - swagger_params_parser
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
      - onError: json_error_handler

